name: 🚀 Déploiement Symfony sur O2switch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📂 Vérifier le dépôt
      uses: actions/checkout@v4

    - name: 🔑 Charger la clé SSH depuis les secrets GitHub
      run: |
        echo "${{ secrets.O2SWITCH_SSH_KEY }}" > private_key
        chmod 600 private_key

    - name: 🚀 Déploiement sur O2switch
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: "epinoche.o2switch.net"  # Remplace par ton domaine O2switch
        username: "gehu1211"  # Ton identifiant SSH
        key: ${{ secrets.O2SWITCH_SSH_KEY }}
        port: 22
        script: |
          echo "✅ Connexion SSH réussie !"
          ls -la ~/www/mediatekformation  # Vérifier que le chemin est correct
          bash ~/www/mediatekformation/deploy.sh
