name: Déploiement Symfony

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 🚀 Déploiement sur O2switch
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: "epinoche.o2switch.net"
        username: "gehu1211"
        key: "digitalexpertize"
        script: "~/www/mediatekformation/deploy.sh"
